/**
 * Render `docs/EVIDENCE.md` from the same data the `/evidence` page reads.
 *
 * An evidence pack that exists twice will eventually say two different things,
 * and the version the Ambassador happens to open will be the stale one. So the
 * markdown is generated, never edited: `pnpm evidence:doc` after any change to
 * `apps/web/lib/evidence.ts`.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  DEPLOYMENT,
  SAMPLE_REPORTS,
  SECTIONS,
  VERIFY_COMMANDS,
  countByStatus,
  type EvidenceStatus,
} from "../apps/web/lib/evidence.ts";

const MARK: Record<EvidenceStatus, string> = {
  done: "**Delivered**",
  partial: "**Partial**",
  todo: "**Outstanding**",
};

const out: string[] = [];
const w = (line = "") => out.push(line);

const outstanding = countByStatus("todo") + countByStatus("partial");

w("# Evidence pack");
w();
w("<!-- Generated by `pnpm evidence:doc` from apps/web/lib/evidence.ts. Do not edit by hand. -->");
w();
w(
  "Every requirement the Statement of Work names, what satisfies it, and where to check it " +
    "without taking anyone's word for it. Section 6.2 of the SOW is verified deliverable by " +
    "deliverable; the tables below follow that order.",
);
w();
w(
  outstanding > 0
    ? `**${outstanding} item${outstanding === 1 ? "" : "s"} ${outstanding === 1 ? "is" : "are"} still outstanding** and marked as such rather than omitted.`
    : "Every item is delivered.",
);
w();
w("## Deployment");
w();
w("| | |");
w("| --- | --- |");
w(`| Network | ${DEPLOYMENT.network} |`);
w(`| Settlement contract | [\`${DEPLOYMENT.contractId}\`](${DEPLOYMENT.contractExplorer}) |`);
w(`| Settlement asset | Testnet USDC — [\`${DEPLOYMENT.usdcSacId}\`](${DEPLOYMENT.usdcExplorer}) |`);
w(`| Deployed | ${DEPLOYMENT.deployedAt} |`);
w(`| Source | ${DEPLOYMENT.repository} |`);
w();

for (const section of SECTIONS) {
  w(`## ${section.title}`);
  w();
  w(`Budget: ${section.budget}`);
  w();
  w(`*Evidence asked for:* ${section.asked}`);
  w();
  for (const item of section.items) {
    w(`### ${MARK[item.status]} — ${item.requirement}`);
    w();
    w(item.detail);
    if (item.refs?.length) {
      w();
      w(
        item.refs
          .map((ref) => `[${ref.label}](${ref.href.startsWith("/") ? `${DEPLOYMENT.repository}${ref.href}` : ref.href})`)
          .join(" · "),
      );
    }
    w();
  }
}

w("## The three sample reports");
w();
w(
  "Built from fixed drafts rather than a live model call, so regenerating them produces these " +
    "hashes exactly. A sample that changed on every run would prove nothing.",
);
w();
w("| Sample | Advisory score | Report hash |");
w("| --- | --- | --- |");
for (const sample of SAMPLE_REPORTS) w(`| \`${sample.name}\` | ${sample.score} / 100 | \`${sample.hash}\` |`);
w();
w("## Check it yourself");
w();
w("Clone the repository and run these. None of them need a wallet, a key, or an API token.");
w();
for (const entry of VERIFY_COMMANDS) w(`- \`${entry.cmd}\` — ${entry.what}`);
w();

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(root, "docs", "EVIDENCE.md");
writeFileSync(target, `${out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`, "utf8");
console.log(`Wrote docs/EVIDENCE.md — ${countByStatus("done")} delivered, ${countByStatus("partial")} partial, ${countByStatus("todo")} outstanding.`);
